name: Actions Workflow

on: [push]

jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: simple-js-action
        uses: actions/helle-world-javascript-action@v1
        with:
          who-to-greet: World!
      - name: log greeting
        run: echo "${{steps.simple-js-action.outputs.time}}"